[package]
name = "gazer"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = { version = "0.64.0", features = ["runtime","derive"] }
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"] }
